[project]
name = "y2tmp3"
version = "1.0.0"
description = "A simple CLI tool to download YouTube videos as MP3 files"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "yt-dlp>=2025.05.22",
]

[project.scripts]
y2tmp3 = "y2tmp3.cli:main"
